---
title: "Coastal Bird Monitoring at Boston Harbor Islands NRA"
output: 
  flexdashboard::flex_dashboard:
    theme: yeti
    orientation: columns
    vertical_layout: fill
    runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(shiny)
#devtools::install_github('aaronweed/NETNCoastalBirds')
library(NETNCoastalBirds)

# read in data files
species_tlu<-read.csv("./data/SppSurvey_tlu.csv")
species<-species_tlu$CommonName
surveys<-read.csv("./data/tlu_surveys.csv")

incub.yr<-read.csv("./data/incub_yr.csv")
incub.day<-read.csv("./data/incub_day.csv")
creche.yr<-read.csv("./data/creche_yr.csv")
creche.day<-read.csv("./data/incub_day.csv")
nests.yr<-read.csv("./data/nests_yr.csv")
incub_raw<-read.csv("./data/incub_raw.csv")
creche_raw<-read.csv("./data/creche_raw.csv")
nests_raw<-read.csv("./data/nests_raw.csv")
amoy_raw<-read.csv("./data/amoy_raw.csv")
amoy_MP<-read.csv("./data/amoy_MP.csv")
proj<-'+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs'
#proj4string(amoy_MP)<-proj

```

Select Species and Survey Cype {.sidebar}
===============================
```{r}

selectInput("species", label = "Select Species", 
            species, selected = "COEI")

selectInput("surveyClass", label = "Select Survey Class", 
            c("Boat", "Ground"))

# radioButtons(inputId = "overlay", label = "Overlay plot",choices=c("Island = island","Species= species","life stage= var"), selected = "life stage")

```

Survey History
=====================================
``` {r surveys, echo=FALSE, warning=FALSE, comment= NA,eval = TRUE}
SpeciesName = reactive({
    species_tlu$Species_Code[species_tlu$CommonName %in% input$species]
    
  })
  
SurveyType = reactive({
    species_tlu$Survey_Type[species_tlu$Survey_Class %in% input$surveyClass & species_tlu$CommonName %in% input$species]
    
  })

renderTable({

 # verify that data inputs produce output
  shiny::validate(
    shiny::need(SurveyType(), message =  "There are no surveys for this species.")
    )
  
 # select survey  data bases on user input 
  if(SurveyType() %in% "Creche"){
    df <-creche_raw
} 
  
  if(SurveyType() %in% "Nest"){
    df <-nests_raw
} 
  
  if(SurveyType() %in% "Incubation"){
    df <-incub_raw
} 
  
  if(SpeciesName() %in% "AMOY" & SurveyType() %in% "Incubation" | SurveyType() %in% "Nest"){
    df <-amoy_raw
}
  
  # create survey matrix
  
  tbl<-NETNCoastalBirds::GetSurveyMat(df=df, species= SpeciesName(), survey= SurveyType())[-c(1)]
      
  
  tbl
  
})

```




View raw survey data
=====================================

``` {r raw_tabl}

  SpeciesName = reactive({
    species_tlu$Species_Code[species_tlu$CommonName %in% input$species]
    
  })
  SurveyType = reactive({
    species_tlu$Survey_Type[species_tlu$Survey_Class %in% input$surveyClass & species_tlu$CommonName %in% input$species]
    
  })
  
DT::renderDataTable({
  # verify that data inputs produce output
  shiny::validate(
    shiny::need(SurveyType(), message =  "There are no surveys for this species.")
    )
  
 # incubation surveys
 if(SurveyType() %in% "Incubation"){
   surveys_raw<-incub_raw %>% 
     dplyr::filter(Species_Code %in% SpeciesName()) %>% 
     dplyr::select(Island,Segment, Date,`Primary Survey` = Survey_Primary, `Life stage` = Species_Unit, Count= Unit_Count, Observer)
   }
 
  # creche surveys
 if(SpeciesName() %in% "COEI" & SurveyType() %in% "Creche") { 
   surveys_raw<-creche_raw %>% 
     dplyr::select(Island,Segment, Date,`Primary Survey` = Survey_Primary,`Life stage` = Species_Unit,Count= Unit_Count, Observer)}
 
  # ground nest surveys
  if(SurveyType() %in% "Nest") { 
    surveys_raw<-nests_raw %>% 
      dplyr::filter(Species_Code %in% SpeciesName())%>% 
      dplyr::select(Island,Segment, Date,`Primary Survey` = Survey_Primary, `Nest Status` = Nest_Status, Nests= Unit_Count, Eggs = Egg_Count, Chicks = Chick_Count, Observer)
  
  } 

  # AMOY mating pairs
  if(SpeciesName() %in% "AMOY" & SurveyType() %in% "Incubation") { 
    surveys_raw<-amoy_raw %>% 
      dplyr::select(Island,Segment, Date,Species_Unit,Unit_Count, Group_Notes)
  
  }
  
   if(nrow(surveys_raw) == 0){print("Data are not collected for that species and survey combination.")}else{
   DT::datatable(surveys_raw,caption = 'Raw survey data', filter = list(position = "top", clear = T, plain= T),fillContainer =T,options = list(pageLength = 10, autoWidth = TRUE))
   }
  
})

```

View annual summary data
=====================================

``` {r sum_table}
library(magrittr)
# select species code from ui input
 SpeciesName = reactive({
    species_tlu$Species_Code[species_tlu$CommonName %in% input$species]
    
  })
     
  ### select raw survey data depending on inputs
  SurveyType = reactive({
    species_tlu$Survey_Type[species_tlu$Survey_Class %in% input$surveyClass & species_tlu$CommonName %in% input$species]
    
  })
  
  
DT::renderDataTable({
  # verify that data inputs produce output
   shiny::validate(
    shiny::need(SurveyType(), message =  "There are no surveys for this species.")
    )
  
    ### select raw survey data depending on inputs
 # incubation surveys
 if(SpeciesName() %in% c("DCCO","GBBG", "HERG") & SurveyType() %in% "Incubation") { 
   surveys_sum<-
     dplyr::filter(incub.yr, Species_Code %in% SpeciesName() & stat %in% "mean") %>% 
     dplyr::select(Island,time,`Raw count`= value,Density = valuePerSurveySize, `Survey Units`= Survey_Units)
   
   }
 
  # creche surveys
 if(SpeciesName() %in% "COEI" & SurveyType() %in% "Creche") { 
   surveys_sum<-
     dplyr::filter(creche.yr, stat %in% "max") %>% 
     dplyr::select(Island,time,`Life stage`= variable,`Raw count`= value,Density = valuePerSurveySize, `Survey Units`= Survey_Units)
  }
 
  # ground nest surveys
  if(SurveyType() %in% "Nest") { 
    surveys_sum<-dplyr::filter(nests.yr, Species_Code %in% SpeciesName()) %>% 
    dplyr::select(Island,time,`Life stage`= variable,`Raw count`= value,Density = valuePerSurveySize, `Survey Units`= Survey_Units)
  }
    
  
   # amoy mATING PAIRS
  if(SpeciesName() %in% "AMOY" & SurveyType() %in% "Incubation") { 
    surveys_sum<-amoy_MP
  
  }
  
  if(nrow(surveys_sum) == 0){"Data are not collected for that species and survey combination."}else{ 
    
  DT::datatable(surveys_sum,caption = 'Summary survey data', filter = list(position = "top", clear = T, plain= T),fillContainer =T,options = list(pageLength = 10, autoWidth = F))
  }
  
})


```

Plot annual counts 
=====================================

``` {r plots,  echo=FALSE, warning=FALSE, comment= NA,eval = TRUE}

SpeciesName = reactive({
    species_tlu$Species_Code[species_tlu$CommonName %in% input$species]
    
  })
  
  SurveyType = reactive({
    species_tlu$Survey_Type[species_tlu$Survey_Class %in% input$surveyClass & species_tlu$CommonName %in% input$species]
    
  })
  
renderPlot({
  
   # verify that data inputs produce output
   shiny::validate(
    shiny::need(SurveyType(), message =  "There are no surveys for this species.")
    )
   
  
  ### select summary  survey data depending on inputs
  
 # incubation surveys
 if(SpeciesName() %in% c("DCCO","GBBG", "HERG") & SurveyType() %in% "Incubation") { 
   
   surveys_sum<-incub.yr[incub.yr$Species_Code %in% SpeciesName(),]
   
   pl<-PlotBirds(surveys_sum, stat= "max", overlay = "var", legend = F, raw_count = T,plot_title = "yes")
   
   }
 
  # creche surveys
 if(SpeciesName() %in% "COEI" & SurveyType() %in% "Creche") { 
   surveys_sum<-creche.yr[creche.yr$stat %in% "max",]
   
   pl<-PlotBirds(surveys_sum, stat= "max", overlay = "var", legend = T, raw_count = T,plot_title = "yes")
   }
 
  # ground nest surveys
  if(SurveyType() %in% "Nest") { 
    surveys_sum<-nests.yr[nests.yr$Species_Code %in% SpeciesName(),]
    
    pl<-PlotBirds(surveys_sum, stat= NA, overlay = "var", legend = T, raw_count = T,plot_title = "yes")
    
  } 
  
  # amoy mATING PAIRS
  if(SpeciesName() %in% "AMOY" & SurveyType() %in% "Incubation") { 
    surveys_sum<-amoy_MP
    
    pl<-PlotBirds(surveys_sum, stat= NA, legend = T, raw_count = T, plot_title = "Mating Pairs detected per year among islands", overlay = "island", facet="variable")
    
    } 

  print(pl)
  
})

```
